### PR TITLE
Add support for buffers

### PR DESCRIPTION
**Pull request by brendan-ta**
Hi @jonkerj, just the same PR from #1.  Relatively new to contributing changes in Github so I figured making a new PR was an easier option for me with the changes in my commit messages and pushing to a different branch.

### CODE REVIEW

**Comment by jonkerj** [comment]
Hi, thanks again for your PR. Re-submitting is not necessary; just force-push your amended commits when you improved them. 

Unfortunately, GH requires me to approve your work before the workflow/pipelines vet/lint the code. Code itself is fine, so if you can amend your `godoc`, I'll approve and we'll see if the linters are happy :-)

**Comment by brendan-ta** [comment]
> Hi, thanks again for your PR. Re-submitting is not necessary; just force-push your amended commits when you improved them.
> 
> Unfortunately, GH requires me to approve your work before the workflow/pipelines vet/lint the code. Code itself is fine, so if you can amend your `godoc`, I'll approve and we'll see if the linters are happy :-)

Apologies for the re-submit, I haven't contributed much so unsure on the exact process that people prefer/expect. 

What did you mean by 'amend your `godoc`'?  Did you want me to make any specific changes to the comments for each of the new functions I added?  or did you want me to add an example to `doc.go`?

**Comment by jonkerj** [comment]
> Apologies for the re-submit, I haven't contributed much so unsure on the exact process that people prefer/expect.

No problem, I'm happy to guide you through it.

> What did you mean by 'amend your `godoc`'? Did you want me to make any specific changes to the comments for each of the new functions I added? or did you want me to add an example to `doc.go`?

You've put some comments before the new exported methods (see review comments above). I'd like you to change them into proper `godoc` compatible comments, so the generated docs on pkg.go.dev will contain your docs. You can do that by changing some of your commits, which I typically do in a workflow like this:

1. `git rebase -i HEAD^^^` (interactively rebase last three commits)
2. Change the words `pick` to `edit` for the commits needing amending
3. Make the requested changes (ie, fix the godocs)
4. `git commit --amend <changed file(s)>`
5. `git rebase --continue` and repeat 3-5
6. `git push --force-with-lease`
7. Update/close review comments on GitHub

**Comment by jonkerj** [comment]
Sorry it took me so lang to respond, I really value your contribution. The comments are (very) OK now, so I approved. But the linter is not happy yet. Fortunately, it is a trivial change :-)

**Comment by brendan-ta** [comment]
> Sorry it took me so lang to respond, I really value your contribution. The comments are (very) OK now, so I approved. But the linter is not happy yet. Fortunately, it is a trivial change :-)

No problems at all, hopefully the linter is happy now

**Comment by jonkerj** [comment]
Congrats, it is merged! I'll release a new version today-ish

**Pull request merged**
